name = "dtiktok"
main = "worker.js"
compatibility_date = "2023-08-14"
workers_dev = false
minify = true

kv_namespaces = [
  { binding = "data", id = "17bef60b14ed4c02ad607ddd2aac18c4", preview_id = "d69ca07021724fdfb3d758c07c487ce7" }
]
